[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 8, y = 5 }
opacity = 0.8
blur = false

[font]
normal = { family = "Maple Mono CN", style = "Regular" }
bold = { family = "Maple Mono CN", style = "bold" }
italic = { family = "Maple Mono CN", style = "italic" }
bold_italic = { family = "Roboto Mono", style = "bold italic" }
size = 7

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
style = { shape = "Beam", blinking = "On" }

[terminal]
shell = { program = "/usr/bin/zsh", args = ["-l"] }

[colors.primary]
background = "#111111"
foreground = "#ebdbb2"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[colors.cursor]
text = "#282828"
cursor = "#ebdbb2"

[keyboard]
bindings = [
    # 复制 (Cmd + C)
    { key = "C", mods = "Command", action = "Copy" },

    # 粘贴 (Cmd + V)
    { key = "V", mods = "Command", action = "Paste" },

    # 查找 (Cmd + F)
    { key = "F", mods = "Command", action = "SearchForward" },

    # 新建窗口 (Cmd + N)
    { key = "N", mods = "Command", action = "CreateNewWindow" },

    # 缩小字体 (Cmd + -)
    { key = "Minus", mods = "Command", action = "DecreaseFontSize" },

    # 放大字体 (Cmd + =)
    { key = "Equals", mods = "Command", action = "IncreaseFontSize" },

    # 恢复默认字体大小 (Cmd + 0)
    { key = "Key0", mods = "Command", action = "ResetFontSize" },

    # 切换全屏 (Cmd + Enter)
    { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" },

    # 切换到具体标签页 (Cmd + 1 ~ Cmd + 9)
    { key = "Key1", mods = "Command", action = "SelectTab1" },
    { key = "Key2", mods = "Command", action = "SelectTab2" },
    { key = "Key3", mods = "Command", action = "SelectTab3" },
    { key = "Key4", mods = "Command", action = "SelectTab4" },
    { key = "Key5", mods = "Command", action = "SelectTab5" },
    { key = "Key6", mods = "Command", action = "SelectTab6" },
    { key = "Key7", mods = "Command", action = "SelectTab7" },
    { key = "Key8", mods = "Command", action = "SelectTab8" },
    { key = "Key9", mods = "Command", action = "SelectTab9" },

    # 隐藏 Alacritty (Cmd + H)
    { key = "H", mods = "Command", action = "Hide" },

    # 隐藏其他应用 (Cmd + Option + H)
    { key = "H", mods = "Command|Option", action = "HideOtherApplications" },
]
